[build.processing.html]
	pretty_urls = true

[[redirects]]
	from = "http://volunteers.torontojs.com/*"
	to = "https://volunteers.torontojs.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "https://volunteers.torontojs.com/*"
	to = "https://volunteer.torontojs.com/:splat"
	status = 301
	force = true

[[redirects]]
	from = "http://volunteer.torontojs.com/*"
	to = "https://volunteer.torontojs.com/:splat"
	status = 301
	force = true
